name: llm-build
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.10
  - pip
  - numpy
  - pandas
  - scikit-learn
  - pyyaml
  - tqdm
  - rich
  - pytorch
  - torchvision
  - torchaudio
  - pip:
      - python-dotenv==1.0.1
      - transformers==4.43.2
      - datasets==2.20.0
      - accelerate==0.33.0
      - tokenizers==0.19.1
      - sentencepiece==0.2.0
      - peft==0.11.1
      - bitsandbytes==0.43.1
      - wandb==0.17.0
